CREATE TABLE IF NOT EXISTS task_list (id bigint generated by default as identity, name varchar(255) not null, primary key (id));
CREATE TABLE IF NOT EXISTS tasks (id bigint generated by default as identity, name varchar(255) not null, tasks_id bigint, primary key (id));
ALTER TABLE tasks ADD FOREIGN KEY (tasks_id) REFERENCES task_list(id);